@echo off
setlocal EnableDelayedExpansion

rem ============================================================================
rem Claude-GLM: Claude Code with Z.ai GLM API
rem Generated by claude-glm installer v{{VERSION}}
rem Plan: {{PLAN_NAME}} | Updated: {{DATE}}
rem ============================================================================

rem ── Clear OAuth tokens to prevent auth conflicts ──
set "ANTHROPIC_AUTH_TOKEN="
set "CLAUDE_CODE_OAUTH_TOKEN="

rem ── API Configuration ──
set "ANTHROPIC_API_KEY={{API_KEY}}"
set "ANTHROPIC_BASE_URL=https://api.z.ai/api/anthropic"
set "API_TIMEOUT_MS=3000000"
set "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1"
set "CLAUDE_CONFIG_DIR=%USERPROFILE%\.claude-glm"

rem ── Model Mappings ({{PLAN_NAME}} plan) ──
set "ANTHROPIC_DEFAULT_OPUS_MODEL={{OPUS_MODEL}}"
set "ANTHROPIC_DEFAULT_SONNET_MODEL={{SONNET_MODEL}}"
set "ANTHROPIC_DEFAULT_HAIKU_MODEL={{HAIKU_MODEL}}"

rem ── Config Bootstrap ──
if not exist "%CLAUDE_CONFIG_DIR%" mkdir "%CLAUDE_CONFIG_DIR%"

if not exist "%CLAUDE_CONFIG_DIR%\.credentials.json" (
  <nul set /p={"apiKeyAuth":{"source":"environment"}}>"%CLAUDE_CONFIG_DIR%\.credentials.json"
)

if not exist "%CLAUDE_CONFIG_DIR%\.claude.json" (
  <nul set /p={"hasCompletedOnboarding":true,"onboardingComplete":true,"customApiKeyResponses":{"approved":[],"rejected":[]},"bypassPermissionsModeAccepted":true}>"%CLAUDE_CONFIG_DIR%\.claude.json"
)

if not exist "%CLAUDE_CONFIG_DIR%\settings.json" (
  <nul set /p={"model":"opus"}>"%CLAUDE_CONFIG_DIR%\settings.json"
)

rem ── Binary Discovery ──

rem Method 1: Native installer
if exist "%USERPROFILE%\.local\bin\claude.exe" (
  "%USERPROFILE%\.local\bin\claude.exe" %*
  exit /b !ERRORLEVEL!
)

rem Method 2: npm global install
if exist "%APPDATA%\npm\claude.cmd" (
  call "%APPDATA%\npm\claude.cmd" %*
  exit /b !ERRORLEVEL!
)

rem Method 3: AppData standalone installer
if exist "%LOCALAPPDATA%\Programs\claude\claude.exe" (
  "%LOCALAPPDATA%\Programs\claude\claude.exe" %*
  exit /b !ERRORLEVEL!
)

rem Method 4: PATH fallback
where claude >nul 2>&1
if %ERRORLEVEL% equ 0 (
  claude %*
  exit /b !ERRORLEVEL!
)

echo ERROR: Claude Code binary not found!
echo.
echo Install Claude Code first:
echo   https://claude.ai/download
exit /b 1
