#!/usr/bin/env bash
# ============================================================================
# Claude-GLM: Claude Code with Z.ai GLM API
# Generated by claude-glm installer v{{VERSION}}
# Plan: {{PLAN_NAME}} | Updated: {{DATE}}
# ============================================================================

# ── Clear OAuth tokens to prevent auth conflicts ──
unset ANTHROPIC_AUTH_TOKEN 2>/dev/null
unset CLAUDE_CODE_OAUTH_TOKEN 2>/dev/null

# ── API Configuration ──
export ANTHROPIC_API_KEY="{{API_KEY}}"
export ANTHROPIC_BASE_URL="https://api.z.ai/api/anthropic"
export API_TIMEOUT_MS="3000000"
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1"
export CLAUDE_CONFIG_DIR="$HOME/.claude-glm"

# ── Model Mappings ({{PLAN_NAME}} plan) ──
export ANTHROPIC_DEFAULT_OPUS_MODEL="{{OPUS_MODEL}}"
export ANTHROPIC_DEFAULT_SONNET_MODEL="{{SONNET_MODEL}}"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="{{HAIKU_MODEL}}"

# ── Config Bootstrap ──
(umask 077; mkdir -p "$CLAUDE_CONFIG_DIR")
[ ! -f "$CLAUDE_CONFIG_DIR/.credentials.json" ] && \
  printf '{"apiKeyAuth":{"source":"environment"}}' > "$CLAUDE_CONFIG_DIR/.credentials.json"
[ ! -f "$CLAUDE_CONFIG_DIR/.claude.json" ] && \
  printf '{"hasCompletedOnboarding":true,"onboardingComplete":true,"customApiKeyResponses":{"approved":[],"rejected":[]},"bypassPermissionsModeAccepted":true}' > "$CLAUDE_CONFIG_DIR/.claude.json"
[ ! -f "$CLAUDE_CONFIG_DIR/settings.json" ] && \
  printf '{"model":"opus"}' > "$CLAUDE_CONFIG_DIR/settings.json"

# ── Binary Discovery ──

# Method 1: Native installer symlink (preferred — always points to latest)
if [ -L "$HOME/.local/bin/claude" ]; then
  CLAUDE_BIN="$(readlink "$HOME/.local/bin/claude" 2>/dev/null || true)"
  if [ -n "$CLAUDE_BIN" ]; then
    # Resolve relative symlinks against symlink's directory
    case "$CLAUDE_BIN" in /*) ;; *) CLAUDE_BIN="$HOME/.local/bin/$CLAUDE_BIN" ;; esac
    if [ -x "$CLAUDE_BIN" ]; then
      exec "$CLAUDE_BIN" "$@"
    fi
  fi
fi

# Method 2: Latest version in versions directory
VERSIONS_DIR="$HOME/.local/share/claude/versions"
if [ -d "$VERSIONS_DIR" ]; then
  LATEST="$(ls "$VERSIONS_DIR" 2>/dev/null | sort -t. -k1,1n -k2,2n -k3,3n | tail -1)"
  if [ -n "$LATEST" ] && [ -x "$VERSIONS_DIR/$LATEST" ]; then
    exec "$VERSIONS_DIR/$LATEST" "$@"
  fi
fi

# Method 3: claude in PATH (avoid recursion)
if command -v claude >/dev/null 2>&1; then
  CLAUDE_PATH="$(command -v claude)"
  case "$(basename "$CLAUDE_PATH")" in
    claude-glm) ;;
    *) exec "$CLAUDE_PATH" "$@" ;;
  esac
fi

printf 'ERROR: Claude Code binary not found!\n\n'
printf 'Install Claude Code first:\n'
printf '  https://claude.ai/download\n'
exit 1
